# Generated by Django 2.0.5 on 2018-05-08 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('company_name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('stop_count', models.IntegerField()),
                ('route_count', models.IntegerField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='carrier',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Settlement'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='carrier',
            unique_together={('user', 'settlement')},
        ),
        migrations.AlterIndexTogether(
            name='carrier',
            index_together={('user', 'settlement')},
        ),
    ]
