# Generated by Django 2.0.5 on 2018-05-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180508_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='check_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settlement',
            name='quarter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
