# Generated by Django 2.0.5 on 2018-05-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180508_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='settlement_type',
            field=models.CharField(choices=[('RG', 'Regular'), ('EL', 'Elite'), ('BO', 'Bonus'), ('OT', 'Other')], default='RG', max_length=2),
        ),
    ]
