# Generated by Django 2.0.5 on 2018-05-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_settlement_settlement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('truck_number', models.IntegerField()),
                ('route_date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('piece_count', models.IntegerField()),
                ('stop_count', models.IntegerField()),
                ('route_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Carrier')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Settlement')),
            ],
        ),
    ]
