# Generated by Django 2.0.5 on 2018-05-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_revenue',
        ),
        migrations.RemoveField(
            model_name='route',
            name='settlement',
        ),
    ]
